-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Czas generowania: 03 Paź 2020, 13:24
-- Wersja serwera: 10.4.14-MariaDB
-- Wersja PHP: 7.2.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Baza danych: `rss`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `title` text COLLATE utf8_polish_ci NOT NULL,
  `date` datetime NOT NULL,
  `content` text COLLATE utf8_polish_ci NOT NULL,
  `link` text COLLATE utf8_polish_ci NOT NULL,
  `dbDate` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

--
-- Zrzut danych tabeli `articles`
--

INSERT INTO `articles` (`id`, `title`, `date`, `content`, `link`, `dbDate`) VALUES
(1, 'Lech zarobił miliony euro. To dopiero bramy finansowego eldorado', '2020-10-02 10:34:23', '<p><a href=\"https://www.rmf24.pl/sport/news-lech-zarobil-miliony-euro-to-dopiero-bramy-finansowego-eldor,nId,4768922\"><img src=\"https://i.iplsc.com/lech-zarobil-miliony-euro-to-dopiero-bramy-finansowego-eldor/000AJR3AHSMOLWSB-C461.jpg\" alt=\"Lech zarobił miliony euro. To dopiero bramy finansowego eldorado\" align=\"left\" /></a>Lech Poznań z ogromnym zastrzykiem finansowym po awansie do fazy grupowej Ligi Europy. Kolejorz zarobił już niespełna 3 miliony euro. W przeliczeniu na polską walutę to ponad 13 milionów złotych. To jednak nie koniec, bo dopiero teraz przed Lechem otwierają się bramy finansowego eldorado. Dzięki temu Kolejorz może odjechać reszcie ligi. Miała to robić Legia, ale czwarty raz z rzędu nie udało się jej awansować do europejskich pucharów.</p><br clear=\"all\" />', 'https://www.rmf24.pl/sport/news-lech-zarobil-miliony-euro-to-dopiero-bramy-finansowego-eldor,nId,4768922', '2020-10-02 13:28:48'),
(2, '\"5 na dobry początek\". Weź udział w biegu i pomóż chorym dzieciom', '2020-10-02 08:08:56', '<p><a href=\"https://www.rmf24.pl/news-5-na-dobry-poczatek-wez-udzial-w-biegu-i-pomoz-chorym-dzieci,nId,4768807\"><img src=\"https://i.iplsc.com/5-na-dobry-poczatek-wez-udzial-w-biegu-i-pomoz-chorym-dzieci/000AJQ9Q1DSX8ECJ-C461.jpg\" alt=\"&quot;5 na dobry początek&quot;. Weź udział w biegu i pomóż chorym dzieciom\" align=\"left\" /></a>Dziś rusza charytatywny biegu &quot;5 na dobry początek&quot;. Jego celem jest zebranie pieniędzy na zakup nowoczesnego sprzętu dla Uniwersyteckiego Szpitala Dziecięcego w Prokocimiu. </p><br clear=\"all\" />', 'https://www.rmf24.pl/news-5-na-dobry-poczatek-wez-udzial-w-biegu-i-pomoz-chorym-dzieci,nId,4768807', '2020-10-02 13:28:48'),
(3, 'Jutro rusza 3. runda RSMP – Rajd Świdnicki Krause', '2020-10-02 06:16:38', '<p><a href=\"https://www.rmf24.pl/sport/news-jutro-rusza-3-runda-rsmp-rajd-swidnicki-krause,nId,4768762\"><img src=\"https://i.iplsc.com/jutro-rusza-3-runda-rsmp-rajd-swidnicki-krause/000AJQ51GV53YM9E-C461.jpg\" alt=\"Jutro rusza 3. runda RSMP – Rajd Świdnicki Krause\" align=\"left\" /></a>Jutro kierowcy rywalizujący w Rajdowych Samochodowych Mistrzostwach Polski rozpoczną ściganie na trasie 48. Rajdu Świdnickiego Krause. Tegoroczna edycja tego dobrze znanego rajdu liczy 120 kilometrów i podzielona będzie na 9 odcinków specjalnych. Liderem RSMP - po dwóch rundach - jest Fin Jari Huttunen.</p><br clear=\"all\" />', 'https://www.rmf24.pl/sport/news-jutro-rusza-3-runda-rsmp-rajd-swidnicki-krause,nId,4768762', '2020-10-02 13:28:48'),
(4, 'Piłkarska Liga Europy: Legia Warszawa wyeliminowana', '2020-10-01 22:04:00', '<p><a href=\"https://www.rmf24.pl/sport/news-pilkarska-liga-europy-legia-warszawa-wyeliminowana,nId,4767402\"><img src=\"https://i.iplsc.com/pilkarska-liga-europy-legia-warszawa-wyeliminowana/000AJPLIP125MPOB-C461.jpg\" alt=\"Piłkarska Liga Europy: Legia Warszawa wyeliminowana\" align=\"left\" /></a>Piłkarze Legii Warszawa przegrali u siebie z Karabachem 0:3 (0:0) w meczu 4., decydującej rundy kwalifikacyjnej Ligi Europy. W fazie grupowej tych rozgrywek wystąpi mistrz Azerbejdżanu</p><br clear=\"all\" />', 'https://www.rmf24.pl/sport/news-pilkarska-liga-europy-legia-warszawa-wyeliminowana,nId,4767402', '2020-10-02 13:28:48'),
(5, 'Lech Poznań awansował do fazy grupowej Ligi Europy. Drużyna wygrała z Royal Charleroi', '2020-10-01 21:16:00', '<p><a href=\"https://www.rmf24.pl/sport/news-lech-poznan-awansowal-do-fazy-grupowej-ligi-europy-druzyna-w,nId,4767359\"><img src=\"https://i.iplsc.com/lech-poznan-awansowal-do-fazy-grupowej-ligi-europy-druzyna-w/000AJPHGLD26RCF4-C461.jpg\" alt=\"Lech Poznań awansował do fazy grupowej Ligi Europy. Drużyna wygrała z Royal Charleroi \" align=\"left\" /></a>Piłkarze Lecha Poznań zwyciężyli z Royal Charleroi 2:1. Wygrana umożliwiła drużynie awans do fazy grupowej Ligi Europy. Bohaterem drugiej połowy spotkania był bramkarz Lecha Filip Bednarek, który obronił rzut karny.\n</p><br clear=\"all\" />', 'https://www.rmf24.pl/sport/news-lech-poznan-awansowal-do-fazy-grupowej-ligi-europy-druzyna-w,nId,4767359', '2020-10-02 13:28:48'),
(6, 'Revolut pozwoli na operacje finansowe na srebrze i złocie', '2020-10-02 13:21:19', '\n       Revolut to powstała w 2015 r. usługa, która cały czas zdobywa nowych użytkowników. Żeby zainteresować sobą kolejne osoby, jej twórcy dodają do niej nowe funkcje. Najnowszym rozwiązaniem jest możliwość operowania w aplikacji mobilnej na srebrze i złocie.\n    ', 'https://www.komputerswiat.pl/aktualnosci/inne/revolut-pozwoli-na-operacje-finansowe-na-srebrze-i-zlocie/jqnjjpw', '2020-10-02 13:28:48'),
(7, 'Diablo i Diablo 2 w nowej wersji. Fanowskie Diablo: Respawned dostaje demo', '2020-10-02 13:10:00', '\n       Odświeżone wersje Diablo i Diablo II to projekty, które wciąż marzą się wielu fanom gier wideo. Niestety, na razie nie mamy żadnych oficjalnych informacji na ten temat takich gier tworzonych przez Blizzarda, ale od czego są fani? W sieci zadebiutowało właśnie demo Diablo: Respawned - gry RPG w świecie tej serii.\n    ', 'https://www.komputerswiat.pl/gamezilla/aktualnosci/diablo-i-diablo-2-w-nowej-wersji-fanowskie-diablo-respawned-dostaje-demo/5r6wdpy', '2020-10-02 13:28:48'),
(8, 'Nvidia opóźnia premierę karty GeForce RTX 3070', '2020-10-02 12:50:57', '\n       Nvidia nie ma niestety najlepszej wiadomości dla osób, które zamierzają kupić GeForce’a RTX 3070. Zieloni zdecydowali się bowiem opóźnić premierę karty, która pojawi się w sklepach dopiero pod koniec tego miesiąca. Firma twierdzi, że tym razem będzie przygotowana na duże zapotrzebowania i zapewnia, że warto będzie czekać.\n    ', 'https://www.komputerswiat.pl/aktualnosci/sprzet/nvidia-opoznia-premiere-karty-geforce-rtx-3070/056nyns', '2020-10-02 13:28:48'),
(9, 'Aż 20 000 pracowników Amazona zarażonych koronawirusem', '2020-10-02 11:32:25', '\n       Pandemia koronawirusa zbiera wielkie żniwo w Stanach Zjednoczonych. COVID-19 nie ominął także pracowników największego na świecie sklepu internetowego. Amazon po raz pierwszy ujawnił statystyki zachorowań, pokazujące, ile osób zatrudnionych w tej firmie uległo zakażeniu.\n    ', 'https://www.komputerswiat.pl/aktualnosci/inne/az-20-000-pracownikow-amazona-zarazonych-koronawirusem/xsf3dbb', '2020-10-02 13:28:48'),
(10, 'Odkryto supermasywną czarną dziurę, która więzi 6 galaktyk', '2020-10-02 11:22:50', '\n       Astronomowie z obserwatorium ESO zaobserwowali sześć galaktyk uwięzionych w sieci grawitacyjnej utkanej przez supermasywną czarną dziurę. Struktura jest bardzo stara i bardzo masywna. Powstała, kiedy Wszechświat miał mniej niż miliard lat, a czarna dziura w jej centrum ma masę miliarda mas Słońca.\n    ', 'https://www.komputerswiat.pl/aktualnosci/nauka-i-technika/odkryto-supermasywna-czarna-dziure-ktora-wiezi-6-galaktyk/w257lfj', '2020-10-02 13:28:48'),
(11, 'Krótkie treningi ale systematyczne', '2017-11-15 20:58:05', '<img src=http://static.xmoon.pl/i/01/850_2_org.jpg width=770 />  <b>\nPoczątki zawsze są najgorsze i to nie tylko w ćwiczeniach. Najgorsze też jest to że efektów spodziewamy się bardzo szybko a ich wyraźny brak bardzo szybko może nas zniechęcić do działania.\n</b> <br/><br/>Może lepiej zacząć małymi krokami. Duży skok w wir ćwiczeń może nie być tak owocny jak byś chciał.<br>\nŁatwiej będzie jak zaczniesz ćwiczyć codziennie w krótkim czasie i nawet w domu. Pomyśl ... ', 'http://xmoon.pl/forma/Krotkie-treningi-ale-systematyczne,1,850,1.html', '2020-10-02 13:28:49'),
(12, 'Czego oczekuje kobieta na randce', '2017-11-15 20:57:37', '<img src=http://static.xmoon.pl/i/02/968_1_org.jpg width=770 />  <b>My ciągle mamy problemy ze zrozumieniem kobiet i ciężko też nam czasem odgadnąć czego mogła by oczekiwać od nas albo kogo tak właściwie szuka. Gdybyśmy to wiedzieli dużo łatwiej moglibyśmy zaimponować jej albo przynajmniej czuć się swobodnie.</b> <br/><br/>Według statystyk kobiety nie są aż tak nieprzewidywalne, wystarczy że będziesz pewny siebie w granicach rozsądku, w miarę dobrze ubrany, bez udziwnień i zadbany, ale też i trochę męski – nie ... ', 'http://xmoon.pl/seks/Czego-oczekuje-kobieta-na-randce,1,968,1.html', '2020-10-02 13:28:49'),
(13, 'Modelka Mathilde Gøhler', '2017-11-13 13:56:59', '<img src=http://static.xmoon.pl/i/00/148_1_org.jpg width=770 />  <b>Pochodzaca z Danii Mathilde Gøhler można bardzo łatwo rozpoznać. Ma niecodzienna śliczna buzię, wspaniałe włosy,a ciało … <br>\nSami zobaczcie.</b> <br/><br/> ', 'http://xmoon.pl/seks/Modelka-Mathilde-Gohler,1,148,1.html', '2020-10-02 13:28:49'),
(14, 'Bolid formuły F1 kontra F18  ', '2017-11-13 11:16:03', '<img src=http://static.xmoon.pl/i/00/179_1_org.jpg width=770 />  <b>A co Wy na to aby zmierzyły się dwa potwory F1 i F18?</b> <br/><br/>Otóż w 2014 został nakręcony materiał w którym bolid Red Bull F1 zmierzył się z maszyną F18 Jet Royal Australian Air Force\n<BR><BR>\nPieknie to wygląda<BR><BR><BR>\n<iframe width=\"560\" height=\"315\" ... ', 'http://xmoon.pl/extreme/Bolid-formuly-F1-kontra-F18,1,179,1.html', '2020-10-02 13:28:49'),
(15, 'Mansa Musa najbogatszy człowiek w historii', '2017-11-12 08:55:22', '<img src=http://static.xmoon.pl/i/01/669_1_org.jpg width=770 />  <b>Mało kto domyśla się że najbogatszy człowiek w historii żył bardzo dawno temu i to nie w Europie czy Bliskim Wschodzie czy Chinach.</b> <br/><br/>Mansa Musa to król Mali, który rządził tamtym krajem w latach 1312-1337.\n<BR><BR>\nJego majątek przeliczając na dzisiejsze pieniądze to niebagatelna kwota 400 miliardów dolarów. Żeby porównać ... ', 'http://xmoon.pl/biznes/Mansa-Musa-najbogatszy-czlowiek-w-historii,1,669,1.html', '2020-10-02 13:28:49'),
(16, 'Revolut wprowadza możliwość inwestowania w srebro i złoto z poziomu aplikacji', '2020-10-02 13:21:19', '\n       Revolut to powstała w 2015 r. usługa, która cały czas zdobywa nowych użytkowników. Żeby zainteresować sobą kolejne osoby, jej twórcy dodają do niej nowe funkcje. Najnowszym rozwiązaniem jest możliwość operowania w aplikacji mobilnej na srebrze i złocie.\n    ', 'https://www.komputerswiat.pl/aktualnosci/inne/revolut-wprowadza-mozliwosc-inwestowania-w-srebro-i-zloto-z-poziomu-aplikacji/jqnjjpw', '2020-10-02 13:49:00'),
(17, 'Windows 10 poinformuje o nadchodzącej śmierci naszego dysku SSD', '2020-10-02 13:45:44', '\n       Microsoft chce, by pliki użytkowników systemów Windows były bezpieczne na ich dyskach SSD. Dlatego wraz z wydaniem nowej poglądowej wersji OS-u dodano opcję informowania o możliwym uszkodzeniu sprzętu, by dać w ten sposób czas użytkownikowi na uratowanie swoich danych.\n    ', 'https://www.komputerswiat.pl/aktualnosci/aplikacje/windows-10-poinformuje-o-nadchodzacej-smierci-naszego-dysku-ssd/01ynsvh', '2020-10-02 14:12:55'),
(18, '​Rusza Rajd Świdnicki-Krause. Na początek miejskie OS-y i legendarny Walim', '2020-10-03 07:00:45', '<p><a href=\"https://www.rmf24.pl/raporty/raport-rajdowe-mistrzostwa-polski/swidnicki/news-rusza-rajd-swidnicki-krause-na-poczatek-miejskie-os-y-i-lege,nId,4770945\"><img src=\"https://i.iplsc.com/rusza-rajd-swidnicki-krause-na-poczatek-miejskie-os-y-i-lege/000AJUN637R9071J-C461.jpg\" alt=\"​Rusza Rajd Świdnicki-Krause. Na początek miejskie OS-y i legendarny Walim\" align=\"left\" /></a>Dziś o 15:30 na stadionie OSiR-u w Świdnicy rozpocznie się 48. edycja Rajdu Świdnickiego-Krause. Na starcie stanie blisko 80 załóg - w tym 14 samochodów R5 - które będą rywalizować w historycznych Rajdowych Samochodowych Mistrzostwach Polski. Trasa liczy 120 kilometrów.</p><br clear=\"all\" />', 'https://www.rmf24.pl/raporty/raport-rajdowe-mistrzostwa-polski/swidnicki/news-rusza-rajd-swidnicki-krause-na-poczatek-miejskie-os-y-i-lege,nId,4770945', '2020-10-03 12:07:12'),
(19, 'Lech Poznań w Lidze Europy: Znamy terminarz meczów', '2020-10-03 01:13:09', '<p><a href=\"https://www.rmf24.pl/sport/news-lech-poznan-w-lidze-europy-znamy-terminarz-meczow,nId,4769624\"><img src=\"https://i.iplsc.com/lech-poznan-w-lidze-europy-znamy-terminarz-meczow/000AJU8UB4MS48SD-C461.jpg\" alt=\"Lech Poznań w Lidze Europy: Znamy terminarz meczów\" align=\"left\" /></a>Lech Poznań rozpocznie rywalizację w grupie D Ligi Europy od meczu na własnym stadionie z Benficą Lizbona 22 października. Również na zakończenie fazy grupowej 10 grudnia zagra u siebie: przeciwko Glasgow Rangers.</p><br clear=\"all\" />', 'https://www.rmf24.pl/sport/news-lech-poznan-w-lidze-europy-znamy-terminarz-meczow,nId,4769624', '2020-10-03 12:07:12'),
(20, 'Rajd Koszyc odwołany z powodu koronawirusa', '2020-10-02 20:03:00', '<p><a href=\"https://www.rmf24.pl/raporty/raport-koronawirus-z-chin/europa/news-rajd-koszyc-odwolany-z-powodu-koronawirusa,nId,4769534\"><img src=\"https://i.iplsc.com/rajd-koszyc-odwolany-z-powodu-koronawirusa/000AJTW9Q7OXK3QI-C461.jpg\" alt=\"Rajd Koszyc odwołany z powodu koronawirusa\" align=\"left\" /></a>Zaostrzenie przez Słowację przepisów związanych z koronawirusem i wprowadzenie stanu wyjątkowego w tym kraju spowodowało odwołanie 46. Rajdu Koszyc, czwartej, ostatniej rundy Rajdowych Samochodowych Mistrzostw Polski. Impreza miała się odbyć w dniach 16 – 18 października.</p><br clear=\"all\" />', 'https://www.rmf24.pl/raporty/raport-koronawirus-z-chin/europa/news-rajd-koszyc-odwolany-z-powodu-koronawirusa,nId,4769534', '2020-10-03 12:07:12'),
(21, 'Iga Świątek awansowała do 1/8 finału French Open', '2020-10-02 19:23:00', '<p><a href=\"https://www.rmf24.pl/raporty/raport-tenis-na-rmf24/najnowszefakty/news-iga-swiatek-awansowala-do-1-8-finalu-french-open,nId,4769512\"><img src=\"https://i.iplsc.com/iga-swiatek-awansowala-do-1-8-finalu-french-open/000AJTTO37OS1OEX-C461.jpg\" alt=\"Iga Świątek awansowała do 1/8 finału French Open \" align=\"left\" /></a>​Tenisistki Iga Świątek i Amerykanka Nicole Melicher awansowały do 1/8 finału debla w wielkoszlemowym French Open. Rozstawione z &quot;12&quot; Niemka Laura Siegemund i Rosjanka Wiera Zwonariowa, triumfatorki niedawnego US Open, skreczowały po przegraniu pierwszego seta 3:6.</p><br clear=\"all\" />', 'https://www.rmf24.pl/raporty/raport-tenis-na-rmf24/najnowszefakty/news-iga-swiatek-awansowala-do-1-8-finalu-french-open,nId,4769512', '2020-10-03 12:07:12'),
(22, 'Piotr Zieliński zakażony koronawirusem', '2020-10-02 15:32:00', '<p><a href=\"https://www.rmf24.pl/raporty/raport-koronawirus-z-chin/europa/news-piotr-zielinski-zakazony-koronawirusem,nId,4769219\"><img src=\"https://i.iplsc.com/piotr-zielinski-zakazony-koronawirusem/000AJS361DQN4MS3-C461.jpg\" alt=\"Piotr Zieliński zakażony koronawirusem\" align=\"left\" /></a>Piłkarz Napoli Piotr Zieliński jest zakażony koronawirusem - poinformował w piątek na Twitterze włoski klub SSC Napoli. Pozytywny wynik testu miał także jeden z członków sztabu szkoleniowego ekipy z Neapolu.\n</p><br clear=\"all\" />', 'https://www.rmf24.pl/raporty/raport-koronawirus-z-chin/europa/news-piotr-zielinski-zakazony-koronawirusem,nId,4769219', '2020-10-03 12:07:12'),
(23, 'Mars 2020 - NASA pozwala śledzić podróż łazika Perseverance na Czerwoną Planetę', '2020-10-03 10:11:00', '\n       Mars 2020 to misja, która rozpoczęła się latem. Wtedy w kosmos wystrzelono łazik Perseverance, który obecnie leci w kierunku Czerwonej Planety. NASA postanowiła udostępnić interaktywną mapę, gdzie można śledzić statek zmierzający ku Marsowi. Możliwe to jest na specjalnej stronie.\n    ', 'https://www.komputerswiat.pl/aktualnosci/nauka-i-technika/mars-2020-nasa-pozwala-sledzic-podroz-lazika-perseverance-na-czerwona-planete/l68jtrq', '2020-10-03 12:07:13'),
(24, 'Airlander 10 - jeden z największych statków powietrznych w historii. Niedługo możemy widywać go częściej', '2020-10-03 09:56:28', '\n       Airlander 10 jest niesamowitą maszyną, która być może ma szansę przywrócić na naszym niebie obecność sterowców. Jednostka ta jest największym statkiem powietrznym na świecie, a jej historia pełna jest, jak to często bywa w przypadku maszyn powietrznych, wzlotów i upadków. Poznajmy ją.\n    ', 'https://www.komputerswiat.pl/artykuly/redakcyjne/airlander-10-jeden-z-najwiekszych-statkow-powietrznych-w-historii-niedlugo-mozemy/vjjcxrw', '2020-10-03 12:07:13'),
(25, 'Microsoft ogłasza nowe usprawnienia dla aplikacji Twój telefon z Windows 10', '2020-10-03 09:16:00', '\n       Twój telefon z Windows 10 to aplikacja, która cały czas jest rozwijana. Microsoft ogłosił kolejne usprawnienia, które zostaną wprowadzone w tym programie. Obejmują one sekcję ustawień, która zostanie przebudowana. Po to, aby można było łatwiej zarządzać urządzeniami i dostępnymi opcjami.\n    ', 'https://www.komputerswiat.pl/aktualnosci/programy/microsoft-oglasza-nowe-usprawnienia-dla-aplikacji-twoj-telefon-z-windows-10/27xtrq8', '2020-10-03 12:07:13'),
(26, 'WhatsApp w końcu pozwoli trwale wyciszyć kontakty. To funkcja, na którą czekało wielu', '2020-10-03 12:02:00', '\n       WhatsApp dostanie jedną z bardziej wyczekiwanych funkcji. To możliwość trwałego wyciszania kontaktów. Obecnie można to zrobić na określony czas. Jednak w becie komunikatora dostrzeżono nową opcję, która umożliwi wyciszenie powiadomień od konkretnej osoby na zawsze.\n    ', 'https://www.komputerswiat.pl/aktualnosci/aplikacje/whatsapp-w-koncu-pozwoli-trwale-wyciszyc-kontakty-to-funkcja-na-ktora-czekalo-wielu/sdvp7ch', '2020-10-03 12:23:49'),
(27, 'Gigabyte Brix Pro – nowe minikomputery z procesorami Intel Tiger Lake', '2020-10-03 11:08:00', '\n       Gigabyte Brix Pro to seria obejmująca trzy nowe minikomputery producenta. Urządzenia są niewielkie i pod obudowami mają procesory Intel Tiger Lake, czyli Core 11. generacji z grafiką Xe. Znajdziemy tu także do 64 GB pamięci operacyjnej RAM czy nawet aż cztery porty HDMI. Zobaczmy sobie, co te komputery Gigabyte\'a oferują.\n    ', 'https://www.komputerswiat.pl/aktualnosci/sprzet/gigabyte-brix-pro-nowe-minikomputery-z-procesorami-intel-tiger-lake/ggqyf3x', '2020-10-03 12:23:49');

--
-- Indeksy dla zrzutów tabel
--

--
-- Indeksy dla tabeli `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT dla tabeli `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
